package com.tencent.mm.plugin.sns.ui;

import com.tencent.mm.k.a;
import com.tencent.mm.plugin.sns.data.d;
import com.tencent.mm.plugin.sns.storage.b;
import com.tencent.mm.plugin.sns.storage.m;
import com.tencent.mm.protocal.c.arf;
import com.tencent.mm.protocal.c.blf;
import com.tencent.mm.protocal.c.bpb;

public final class ay {
    public int aac;
    public String jPV;
    public String mAppName;
    public blf qEi;
    public m qEj;
    public bpb qEn;
    public d rPJ;
    public CharSequence rPK = null;
    public a rPL;
    public String rPM;
    public long rPN;
    public String rPO;
    public int rPP;
    public int rPQ;
    public int rPR;
    public boolean rPS;
    public String rPT;
    public String rPU;
    public com.tencent.mm.plugin.sns.storage.a rPV;
    public b rPW;
    public String rPX;
    public String rPY;
    public String rPZ;
    public com.tencent.mm.vending.d.b<com.tencent.mm.vending.j.a> rQA;
    public boolean rQB;
    public String rQC;
    public arf rQD;
    public String rQa;
    public String rQb;
    public boolean rQc;
    public boolean rQd;
    public boolean rQe;
    public int rQf;
    public boolean rQg;
    public String rQh;
    public boolean rQi;
    public boolean rQj;
    public boolean rQk;
    public boolean rQl;
    public String rQm;
    public String rQn;
    public boolean rQo;
    public boolean rQp;
    public int rQq;
    public boolean rQr;
    public boolean rQs;
    public String rQt;
    public boolean rQu;
    public boolean rQv;
    public int rQw;
    public double rQx;
    public com.tencent.mm.vending.d.b<com.tencent.mm.vending.j.a> rQy;
    public com.tencent.mm.vending.d.b<com.tencent.mm.vending.j.a> rQz;
    public boolean rxi;
    public String ryG;
}
