package com.tencent.mm.compatible.e;

import com.tencent.mm.sdk.platformtools.x;

public final class k {
    public int gGA = -1;
    public int gGB = -1;
    public int gGC = -1;
    public int gGD = -1;
    public int gGE = -1;
    public int gGF = -1;
    public int gGG = -1;
    public int gGH = -1;
    public int gGI = -1;
    public int gGJ = -1;
    public int gGK = -1;
    public int gGL = -1;
    public int gGM = -1;
    public int gGN = -1;
    public int gGO = -1;
    public double gGP = -1.0d;
    public int gGQ = -1;
    public int gGR = -1;
    public int gGS = -1;
    public int gGT = -1;
    public String gGU = null;
    public String gGV = null;
    public String gGW = null;
    public String gGX = null;
    public String gGY = null;
    public String gGZ = null;
    public int gGn = -1;
    public int gGo = -1;
    public int gGp = -1;
    public int gGq = -1;
    public int gGr = -1;
    public int gGs = -1;
    public int gGt = -1;
    public int gGu = -1;
    public boolean gGv = false;
    public int gGw = -1;
    public int gGx = -1;
    public int gGy = -1;
    public int gGz = -1;
    public String gHa = null;
    public String gHb = null;
    public String gHc = null;
    public String gHd = null;
    public String gHe = null;
    public String gHf = null;
    public String gHg = null;
    public int gHh = -1;
    public int gHi = 2;
    public int gHj = 1;
    public int gHk = 1;
    public int gHl = -1;

    public k() {
        reset();
    }

    public final void reset() {
        this.gGn = -1;
        this.gGo = -1;
        this.gGp = -1;
        this.gGq = -1;
        this.gGr = -1;
        this.gGs = -1;
        this.gGu = -1;
        this.gGt = -1;
        this.gGx = -1;
        this.gGy = -1;
        this.gGz = -1;
        this.gGA = -1;
        this.gGv = false;
        this.gGw = -1;
        this.gGB = -1;
        this.gGC = -1;
        this.gGD = -1;
        this.gGE = -1;
        this.gGF = -1;
        this.gGI = -1;
        this.gGH = -1;
        this.gGJ = -1;
        this.gGK = -1;
        this.gGG = -1;
        this.gGJ = -1;
        this.gGK = -1;
        this.gGN = -1;
        this.gGQ = -1;
        this.gGR = -1;
        this.gGS = -1;
        this.gGT = -1;
        this.gGU = null;
        this.gGV = null;
        this.gGW = null;
        this.gGX = null;
        this.gGL = -1;
        this.gGY = null;
        this.gGZ = null;
        this.gHa = null;
        this.gHb = null;
        this.gHc = null;
        this.gHd = null;
        this.gGM = -1;
        this.gHe = null;
        this.gHf = null;
        this.gHg = null;
        this.gHh = -1;
        this.gHi = 2;
        this.gHj = 1;
        this.gHk = 1;
        this.gGO = -1;
    }

    public final void dump() {
        x.d("MicroMsg.CommonInfo", "js " + this.gGn);
        x.d("MicroMsg.CommonInfo", "stopBluetoothInBR " + this.gGo);
        x.d("MicroMsg.CommonInfo", "stopBluetoothInBU " + this.gGp);
        x.d("MicroMsg.CommonInfo", "setBluetoothScoOn " + this.gGr);
        x.d("MicroMsg.CommonInfo", "startBluetoothSco " + this.gGq);
        x.d("MicroMsg.CommonInfo", "voiceSearchFastMode " + this.gGs);
        x.d("MicroMsg.CommonInfo", "pcmReadMode " + this.gGu);
        x.d("MicroMsg.CommonInfo", "pcmBufferRate " + this.gGt);
        x.d("MicroMsg.CommonInfo", "audioPrePro " + this.gGx);
        x.d("MicroMsg.CommonInfo", "voicemsgfd " + this.gGy);
        x.d("MicroMsg.CommonInfo", "htcvoicemode " + this.gGz);
        x.d("MicroMsg.CommonInfo", "samsungvoicemode " + this.gGA);
        x.d("MicroMsg.CommonInfo", "speexBufferRate " + this.gGB);
        x.d("MicroMsg.CommonInfo", "linespe " + this.gGC);
        x.d("MicroMsg.CommonInfo", "fixspan " + this.gGN);
        x.d("MicroMsg.CommonInfo", "extvideo " + this.gGD);
        x.d("MicroMsg.CommonInfo", "extvideosam " + this.gGE);
        x.d("MicroMsg.CommonInfo", "sysvideodegree " + this.gGF);
        x.d("MicroMsg.CommonInfo", "mmnotify " + this.gGI);
        x.d("MicroMsg.CommonInfo", "extsharevcard " + this.gGH);
        x.d("MicroMsg.CommonInfo", "audioformat " + this.gGJ);
        x.d("MicroMsg.CommonInfo", "qrcam " + this.gGK);
        x.d("MicroMsg.CommonInfo", "mBase " + this.gGU);
        x.d("MicroMsg.CommonInfo", "mPackageInfo " + this.gGV);
        x.d("MicroMsg.CommonInfo", "mClassLoader " + this.gGW);
        x.d("MicroMsg.CommonInfo", "mResources " + this.gGX);
        x.d("MicroMsg.CommonInfo", "sysvideofp " + this.gGL);
        x.d("MicroMsg.CommonInfo", "extstoragedir " + this.gGY);
        x.d("MicroMsg.CommonInfo", "extpubdir " + this.gGZ);
        x.d("MicroMsg.CommonInfo", "extdatadir " + this.gHa);
        x.d("MicroMsg.CommonInfo", "extrootdir " + this.gHb);
        x.d("MicroMsg.CommonInfo", "extstoragestate " + this.gHc);
        x.d("MicroMsg.CommonInfo", "extcachedir " + this.gHd);
        x.d("MicroMsg.CommonInfo", "extvideoplayer " + this.gGM);
        x.d("MicroMsg.CommonInfo", "loadDrawable " + this.gHe);
        x.d("MicroMsg.CommonInfo", "loadXmlResourceParser " + this.gHf);
        x.d("MicroMsg.CommonInfo", "voipAudioPrePro " + this.gGQ);
        x.d("MicroMsg.CommonInfo", "voipAudioPreProNS " + this.gGR);
        x.d("MicroMsg.CommonInfo", "voipAudioPreProAEC " + this.gGS);
        x.d("MicroMsg.CommonInfo", "voipAudioPreProAGC " + this.gGT);
        x.d("MicroMsg.CommonInfo", "sight full screen type " + this.gHg);
        x.d("MicroMsg.CommonInfo", "checkSightDraftMd5 " + this.gHi);
        x.d("MicroMsg.CommonInfo", "swipeBackConfig " + this.gHj);
        x.d("MicroMsg.CommonInfo", "qrCodeZoom " + this.gGO);
    }
}
